# -*- coding: utf-8 -*-
# Copyright 2017 Dunbar Cybersecurity.
#
# This file is part of Cyphon Engine.
#
# Cyphon Engine is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Cyphon Engine is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cyphon Engine. If not, see <http://www.gnu.org/licenses/>.
#
# Generated by Django 1.11.2 on 2017-11-28 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datamungers', '0001_initial'),
        ('supplychains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('munger', models.ForeignKey(help_text='The Data Munger used to process the data obtained through the Supply Chain.', on_delete=django.db.models.deletion.CASCADE, related_name='procurements', related_query_name='procurement', to='datamungers.DataMunger', verbose_name='data munger')),
                ('supply_chain', models.ForeignKey(help_text='The Supply Chain used to acquire data.', on_delete=django.db.models.deletion.CASCADE, related_name='procurements', related_query_name='procurement', to='supplychains.SupplyChain', verbose_name='supply chain')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='procurement',
            unique_together=set([('supply_chain', 'munger')]),
        ),
    ]
