# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-28 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datamungers', '0001_initial'),
        ('supplychains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('munger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamungers.DataMunger')),
                ('supply_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurements', related_query_name='procurement', to='supplychains.SupplyChain', verbose_name='supply chain')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='procurement',
            unique_together=set([('supply_chain', 'munger')]),
        ),
    ]
