# -*- coding: utf-8 -*-
# Copyright 2017 Dunbar Cybersecurity.
#
# This file is part of Cyphon Engine.
#
# Cyphon Engine is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Cyphon Engine is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cyphon Engine. If not, see <http://www.gnu.org/licenses/>.
#
# Generated by Django 1.11.2 on 2017-12-12 16:05
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0014_remove_alert_notes'),
        ('procurements', '0001_initial'),
        ('distilleries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='input data')),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('doc_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='document id')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', related_query_name='supply_order', to='alerts.Alert', verbose_name='alert')),
                ('distillery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='distilleries.Distillery', verbose_name='distillery')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', related_query_name='supply_order', to='procurements.Procurement', verbose_name='procurement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'supply order',
                'verbose_name_plural': 'supply orders',
                'ordering': ['-id'],
            },
        ),
    ]
