# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-04 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0014_remove_alert_notes'),
        ('procurements', '0002_auto_20171204_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', related_query_name='supply_order', to='alerts.Alert', verbose_name='alert')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', related_query_name='supply_order', to='procurements.Procurement', verbose_name='procurement')),
            ],
            options={
                'verbose_name_plural': 'supply orders',
                'verbose_name': 'supply order',
            },
        ),
    ]
