# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-07 20:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0014_remove_alert_notes'),
        ('procurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', related_query_name='supply_order', to='alerts.Alert', verbose_name='alert')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', related_query_name='supply_order', to='procurements.Procurement', verbose_name='procurement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'supply order',
                'verbose_name_plural': 'supply orders',
            },
        ),
    ]
