# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 20:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=64, verbose_name='parameter name')),
                ('param_type', models.CharField(choices=[('BooleanField', 'BooleanField'), ('CharField', 'CharField'), ('ChoiceField', 'ChoiceField'), ('DateTimeField', 'DateTimeField'), ('EmailField', 'EmailField'), ('FileField', 'FileField'), ('FloatField', 'FloatField'), ('IntegerField', 'IntegerField'), ('GenericIPAddressField', 'IPAddressField'), ('ListField', 'ListField'), ('PointField', 'PointField'), ('TextField', 'TextField'), ('URLField', 'URLField'), ('EmbeddedDocument', 'EmbeddedDocument')], max_length=64, verbose_name='parameter type')),
                ('default', models.CharField(max_length=255, verbose_name='default value')),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=2), blank=True, null=True, size=None, verbose_name='choices')),
                ('required', models.BooleanField(default=False, verbose_name='required')),
                ('help_text', models.CharField(max_length=255, verbose_name='help text')),
                ('verbose_name', models.CharField(max_length=255, verbose_name='verbose name')),
            ],
            options={
                'verbose_name': 'parameter',
                'verbose_name_plural': 'parameters',
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_module', models.CharField(default='handlers', help_text='The module that will handle the API request.', max_length=32, validators=[django.core.validators.RegexValidator('[a-zA-Z_][a-zA-Z0-9_]*', 'Not a valid Python identifier')])),
                ('api_class', models.CharField(help_text='The class that will handle the API request.', max_length=32, validators=[django.core.validators.RegexValidator('[a-zA-Z_][a-zA-Z0-9_]*', 'Not a valid Python identifier')])),
                ('visa_required', models.BooleanField(default=False, help_text='Whether API calls are restricted by a Visa.')),
                ('url', models.URLField(verbose_name='URL')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'requisition',
                'verbose_name_plural': 'requisitions',
            },
        ),
        migrations.AddField(
            model_name='parameter',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisitions.Requisition', verbose_name='requisition'),
        ),
        migrations.AlterUniqueTogether(
            name='requisition',
            unique_together=set([('platform', 'api_class')]),
        ),
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together=set([('requisition', 'param_name')]),
        ),
    ]
