# -*- coding: utf-8 -*-
# Copyright 2017 Dunbar Cybersecurity.
#
# This file is part of Cyphon Engine.
#
# Cyphon Engine is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Cyphon Engine is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cyphon Engine. If not, see <http://www.gnu.org/licenses/>.
#
# Generated by Django 1.11.2 on 2017-11-02 20:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(help_text='The name of the parameter in the API request.', max_length=64, verbose_name='parameter name')),
                ('param_type', models.CharField(choices=[('BooleanField', 'BooleanField'), ('CharField', 'CharField'), ('ChoiceField', 'ChoiceField'), ('DateTimeField', 'DateTimeField'), ('EmailField', 'EmailField'), ('FileField', 'FileField'), ('FloatField', 'FloatField'), ('IntegerField', 'IntegerField'), ('GenericIPAddressField', 'IPAddressField'), ('ListField', 'ListField'), ('PointField', 'PointField'), ('TextField', 'TextField'), ('URLField', 'URLField'), ('EmbeddedDocument', 'EmbeddedDocument')], help_text='The data type of the parameter.', max_length=64, verbose_name='parameter type')),
                ('default', models.CharField(blank=True, help_text='The default value for the parameter.', max_length=255, null=True, verbose_name='default value')),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=2), blank=True, help_text='A list of choices for the parameter, in the format: [value, label], [value, label]"', null=True, size=None, verbose_name='choices')),
                ('required', models.BooleanField(default=False, help_text='Whether the paremeter is required to fulfill the request.', verbose_name='required')),
                ('help_text', models.CharField(blank=True, help_text='An explanation of the parameter to help users understand its purpose.', max_length=255, null=True, verbose_name='help text')),
                ('verbose_name', models.CharField(blank=True, help_text='A human-readable name for the parameter.', max_length=255, null=True, verbose_name='verbose name')),
            ],
            options={
                'verbose_name': 'parameter',
                'verbose_name_plural': 'parameters',
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_module', models.CharField(default='handlers', help_text='The module that will handle the API request.', max_length=32, validators=[django.core.validators.RegexValidator('[a-zA-Z_][a-zA-Z0-9_]*', 'Not a valid Python identifier')])),
                ('api_class', models.CharField(help_text='The class that will handle the API request.', max_length=32, validators=[django.core.validators.RegexValidator('[a-zA-Z_][a-zA-Z0-9_]*', 'Not a valid Python identifier')])),
                ('visa_required', models.BooleanField(default=False, help_text='Whether API calls are restricted by a Visa.')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'requisition',
                'verbose_name_plural': 'requisitions',
            },
        ),
        migrations.AddField(
            model_name='parameter',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', related_query_name='parameter', to='requisitions.Requisition', verbose_name='requisition'),
        ),
        migrations.AlterUniqueTogether(
            name='requisition',
            unique_together=set([('platform', 'api_class')]),
        ),
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together=set([('requisition', 'param_name')]),
        ),
    ]
