# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-07 20:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stamps', '0001_initial'),
        ('supplyorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='data')),
                ('stamp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stamps.Stamp', verbose_name='stamp')),
                ('supply_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manifests', related_query_name='manifest', to='supplyorders.SupplyOrder', verbose_name='supply order')),
            ],
            options={
                'verbose_name_plural': 'manifests',
                'verbose_name': 'Manifest',
            },
        ),
    ]
